
title: Jekyll notPlugins
email: matthew@botinabox.ca
description: >-
 Enhance the functionality of a Jekyll website without using plugins (GitHub Pages-friendly)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jekyll-notplugins.botinabox.ca" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: BotInABoxER
github_username:  BotInABoxER

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
plugins:
  - jekyll-feed
